"""empty message

Revision ID: 04af8324442f
Revises: 
Create Date: 2018-05-25 13:18:49.647778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04af8324442f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhosting_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('alt_email', sa.String(length=100), nullable=False),
    sa.Column('hosted_by_soge', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('has_site', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('userid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('oldPassword', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('changedPass', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('role', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('s1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('s2', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('s3', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('s4', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lastSeen', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('webhosting_survey')
    # ### end Alembic commands ###
