"""empty message

Revision ID: 5275ac7fa2e6
Revises: aa4e62de4fed
Create Date: 2018-05-25 15:44:32.521160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5275ac7fa2e6'
down_revision = 'aa4e62de4fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_survey', 'shared_space_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('webhosting_survey', 'website_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhosting_survey', 'website_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('shared_survey', 'shared_space_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
