"""empty message

Revision ID: 592195ecc48a
Revises: 5275ac7fa2e6
Create Date: 2018-05-25 15:46:08.216189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '592195ecc48a'
down_revision = '5275ac7fa2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_survey', 'process_status',
               existing_type=mysql.ENUM(u'1', u'2', u'3', u'4', u'5'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_survey', 'process_status',
               existing_type=mysql.ENUM(u'1', u'2', u'3', u'4', u'5'),
               nullable=False)
    # ### end Alembic commands ###
