"""empty message

Revision ID: 7ea9b92d6595
Revises: 
Create Date: 2018-08-06 11:56:52.111631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea9b92d6595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PI_username', sa.String(length=8), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('is_soge_hosted', sa.Enum('Y', 'N'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PI_username', sa.String(length=8), nullable=False),
    sa.Column('folder_name', sa.String(length=30), nullable=False),
    sa.Column('storage_type', sa.Enum('linux', 'windows'), nullable=True),
    sa.Column('is_acl_correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information_asset_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('alt_email', sa.String(length=100), nullable=False),
    sa.Column('has_assets', sa.Boolean(), nullable=True),
    sa.Column('asset_type', sa.Enum('Application / System', 'Information / data sets (digital)', 'Information / data sets (physical)', 'Technology (Mobile device - University issued)', 'Technology (Mobile device - Personal)', 'Technology (Desktop)', 'Technology (Server)', 'Technology (Network)', 'Technology (Telephony)', 'Physical (HVAC - Heating, ventilation or air conditioning)', 'Physical (Entry system)', 'Service provider (Cloud)', 'Service provider (IT service)'), nullable=True),
    sa.Column('asset_name', sa.String(length=100), nullable=True),
    sa.Column('asset_owner', sa.String(length=100), nullable=True),
    sa.Column('other_details', sa.Text(), nullable=True),
    sa.Column('data_classification', sa.Enum('Private', 'Public', 'Internal'), nullable=True),
    sa.Column('data_integrity', sa.Enum('Low', 'Medium', 'High'), nullable=True),
    sa.Column('data_availability', sa.Enum('Low', 'Medium', 'High'), nullable=True),
    sa.Column('recovery_time_objective', sa.Enum('within 2 hours', 'within 6 hours', 'within 24 hours', 'within 72 hours'), nullable=True),
    sa.Column('recovery_point_objective', sa.Enum('within 2 hours', 'within 6 hours', 'within 24 hours', 'within 72 hours'), nullable=True),
    sa.Column('supply_media', sa.String(length=200), nullable=True),
    sa.Column('file_size_estimate', sa.String(length=20), nullable=True),
    sa.Column('file_size_final', sa.String(length=20), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('Administrative', 'Research'), nullable=True),
    sa.Column('linux_or_windows', sa.Enum('linux', 'windows'), nullable=True),
    sa.Column('shared_or_personal', sa.Enum('home', 'shared'), nullable=True),
    sa.Column('is_data_personal', sa.Boolean(), nullable=False),
    sa.Column('curec_accepted', sa.Boolean(), nullable=False),
    sa.Column('curec_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('me', 'other'), nullable=False),
    sa.Column('license_or_data_source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('alt_email', sa.String(length=100), nullable=False),
    sa.Column('uses_third_parties', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('service_user', sa.String(length=100), nullable=True),
    sa.Column('Supplier', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('information_type', sa.Text(), nullable=True),
    sa.Column('division', sa.Enum('social_sci', 'humanities'), nullable=True),
    sa.Column('data_classification', sa.Enum('Private', 'Public', 'Internal'), nullable=True),
    sa.Column('data_volume_records', sa.Enum('<1000', '1000-4999', '5000-10k', '>10k'), nullable=True),
    sa.Column('data_compliance', sa.Enum('Unspecific', 'Specific'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('known_third_party_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.Enum('infrastructure', 'platform', 'software', 'cots', 'custom_software', 'outsourced_service_provider', 'other'), nullable=True),
    sa.Column('service_owner_email', sa.String(length=100), nullable=True),
    sa.Column('data_location', sa.Enum('UK', 'EEA', 'non-EEA'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('alt_email', sa.String(length=100), nullable=False),
    sa.Column('has_data', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('group', sa.Enum('15_20deg_water_resources', 'arve', 'beta-diversity', 'carina', 'clarify', 'ComputationalScience', 'do4models', 'EcosystemsLab_TLS', 'enso_flavours', 'fennec', 'gem', 'ghm', 'gwava', 'hiasa', 'impala', 'leaf-gpu', 'leap', 'marius', 'mistral', 'mooredrought', 'okvbasin_sdm', 'pollcurb', 'reach', 'river-routing', 'seviri_dust', 'sfp-datascience', 'soge_routines', 'titan', 'tnc', 'umfula', 'weather_attribution', 'Other'), nullable=False),
    sa.Column('other_group', sa.String(length=20), nullable=True),
    sa.Column('shared_space_id', sa.Integer(), nullable=True),
    sa.Column('supply_media', sa.String(length=200), nullable=True),
    sa.Column('file_size_estimate', sa.String(length=20), nullable=True),
    sa.Column('file_size_final', sa.String(length=20), nullable=True),
    sa.Column('format_name', sa.String(length=100), nullable=True),
    sa.Column('use_constraints', sa.Text(), nullable=True),
    sa.Column('public_access_constraints', sa.Text(), nullable=True),
    sa.Column('process_status', sa.Enum('1', '2', '3', '4', '5'), nullable=True),
    sa.Column('process_steps_description', sa.Text(), nullable=True),
    sa.Column('lineage', sa.Text(), nullable=True),
    sa.Column('experimental_design', sa.Text(), nullable=True),
    sa.Column('collection_generation_transformation_methods', sa.Text(), nullable=True),
    sa.Column('fieldwork_lab_instrumentation', sa.Text(), nullable=True),
    sa.Column('analytical_methods', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shared_space_id'], ['shared_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhosting_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('alt_email', sa.String(length=100), nullable=False),
    sa.Column('hosted_by_soge', sa.Enum('I', 'E'), nullable=True),
    sa.Column('has_site', sa.Enum('Y', 'N'), nullable=True),
    sa.Column('site', sa.Enum('first site', 'Other'), nullable=True),
    sa.Column('other_site', sa.String(length=20), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhosting_survey')
    op.drop_table('shared_survey')
    op.drop_table('known_third_party_supplier')
    op.drop_table('third_party_register')
    op.drop_table('information_asset_inventory')
    op.drop_table('shared_space')
    op.drop_table('website')
    # ### end Alembic commands ###
