"""empty message

Revision ID: a15f081c23d6
Revises: f7e730bc46d0
Create Date: 2018-05-25 15:59:21.840585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a15f081c23d6'
down_revision = 'f7e730bc46d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_survey', 'process_status',
               existing_type=mysql.ENUM(u'1', u'2', u'3', u'4', u'5'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_survey', 'process_status',
               existing_type=mysql.ENUM(u'1', u'2', u'3', u'4', u'5'),
               nullable=False)
    # ### end Alembic commands ###
