"""empty message

Revision ID: aa4e62de4fed
Revises: 9ad02fe21ec4
Create Date: 2018-05-25 14:45:46.352503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4e62de4fed'
down_revision = '9ad02fe21ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhosting_survey', sa.Column('website_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'webhosting_survey', 'website', ['website_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhosting_survey', type_='foreignkey')
    op.drop_column('webhosting_survey', 'website_id')
    # ### end Alembic commands ###
