"""empty message

Revision ID: be2fda7cacff
Revises: 04af8324442f
Create Date: 2018-05-25 13:38:26.126889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be2fda7cacff'
down_revision = '04af8324442f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PI_username', sa.String(length=8), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('is_soge_hosted', sa.Enum('Y', 'N'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'webhosting_survey', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'webhosting_survey', sa.Column('url', mysql.VARCHAR(length=100), nullable=False))
    op.drop_table('website')
    # ### end Alembic commands ###
