"""empty message

Revision ID: f7e730bc46d0
Revises: 592195ecc48a
Create Date: 2018-05-25 15:47:42.131194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7e730bc46d0'
down_revision = '592195ecc48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhosting_survey', 'site',
               existing_type=mysql.ENUM(u'first site', u'Other'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhosting_survey', 'site',
               existing_type=mysql.ENUM(u'first site', u'Other'),
               nullable=False)
    # ### end Alembic commands ###
